const City = [
	{ id: 1, NameRU: 'Москва', NameEU: 'Moscow' },
	{ id: 2, NameRU: 'Санкт-Петербург', NameEU: 'Saint Petersburg' },
	{ id: 3, NameRU: 'Новосибирск', NameEU: 'Novosibirsk' },
	{ id: 4, NameRU: 'Екатеринбург', NameEU: 'Yekaterinburg' },
	{ id: 5, NameRU: 'Нижний Новгород', NameEU: 'Nizhny Novgorod' },
	{ id: 6, NameRU: 'Казань', NameEU: 'Kazan' },
	{ id: 7, NameRU: 'Челябинск', NameEU: 'Chelyabinsk' },
	{ id: 8, NameRU: 'Омск', NameEU: 'Omsk' },
	{ id: 9, NameRU: 'Самара', NameEU: 'Samara' },
	{ id: 10, NameRU: 'Ростов-на-Дону', NameEU: 'Rostov-on-Don' },
	{ id: 11, NameRU: 'Уфа', NameEU: 'Ufa' },
	{ id: 12, NameRU: 'Красноярск', NameEU: 'Krasnoyarsk' },
	{ id: 13, NameRU: 'Воронеж', NameEU: 'Voronezh' },
	{ id: 14, NameRU: 'Пермь', NameEU: 'Perm' },
	{ id: 15, NameRU: 'Волгоград', NameEU: 'Volgograd' },
	{ id: 16, NameRU: 'Краснодар', NameEU: 'Krasnodar' },
	{ id: 17, NameRU: 'Саратов', NameEU: 'Saratov' },
	{ id: 18, NameRU: 'Тюмень', NameEU: 'Tyumen' },
	{ id: 19, NameRU: 'Тольятти', NameEU: 'Tolyatti' },
	{ id: 20, NameRU: 'Ижевск', NameEU: 'Izhevsk' },
	{ id: 21, NameRU: 'Барнаул', NameEU: 'Barnaul' },
	{ id: 22, NameRU: 'Ульяновск', NameEU: 'Ulyanovsk' },
	{ id: 23, NameRU: 'Иркутск', NameEU: 'Irkutsk' },
	{ id: 24, NameRU: 'Ярославль', NameEU: 'Yaroslavl' },
	{ id: 25, NameRU: 'Хабаровск', NameEU: 'Khabarovsk' },
	{ id: 26, NameRU: 'Владивосток', NameEU: 'Vladivostok' },
	{ id: 27, NameRU: 'Махачкала', NameEU: 'Makhachkala' },
	{ id: 28, NameRU: 'Томск', NameEU: 'Tomsk' },
	{ id: 29, NameRU: 'Оренбург', NameEU: 'Orenburg' },
	{ id: 30, NameRU: 'Кемерово', NameEU: 'Kemerovo' }
];


export default City;